### ISSUE TITLE
Create a configuration file for parameters

### ISSUE THREAD

**Issue by oskarsari** [ultra-trace-systems/mascope#166]
In GitLab by @oskarsa on Feb 20, 2024, 14:43

**Comment by philip-chernonog** [comment]
Potential library to use

https://github.com/dynaconf/dynaconf

**Comment by oskarsari** [comment]
In [this PR](https://github.com/Karsa-Oy/Mascope/pull/611) an endpoint to retrieve parameters from the backend was created, which is supposed to be developed further to include all _parameters_ needed to be synced between the frontend and backend.

On the other hand the _configuration_ of the application is handled by the [runtime config files](https://github.com/Karsa-Oy/Mascope?tab=readme-ov-file#runtime-config).

While all the _parameters_ are not yet included, the mechanism is there so closing this issue.
