### ISSUE TITLE
Migrate away from the xlsx package

### ISSUE THREAD

**Issue by ixxie** [ultra-trace-systems/mascope#314]
The package is used by the frontend to export spreadsheet files, but has multiple vulnerabilities and is not maintained.

Possible alternative: https://www.npmjs.com/package/write-excel-file

**Comment by oskarsari** [comment]
I'm thinking we could probably use the [PrimeVue DataTable Export functionality](https://primevue.org/datatable/#export)

**Comment by ixxie** [comment]
We could, but the current import produces a multisheet XLSX and sets column widths. Neither of these functionalities would be available in a simple CSV export: the user would need to export every table separately...

**Comment by ixxie** [comment]
I've discovered [SheetJS](https://docs.sheetjs.com/) which offers full multisheet support.
