### ISSUE TITLE
Compare Mascope peak fits with Tracefinder

### ISSUE THREAD

**Issue by oskarsari** [ultra-trace-systems/mascope#365]

**Comment by ghost** [comment]
We got reports from the lab team that the peak shape in several samples was off in Mascope compared to Tracefinder. Investigation revealed that most of the peaks in both apps look similar except the one at 305.92 Th. The peak in the deployed version at https://192.168.1.99/ (Orbitrap server) was "doubled". The issue does not persist in the latest version of the Mascope (the calibration is off in the last row). 

<p align="center">
	<img src="https://github.com/Karsa-Oy/Mascope/assets/162983707/8d44b289-7bcc-44fa-a41e-c71d4af34d7b" width="700"/></p>

 The time series looks better in the latest Mascope version as well.

<p align="center">
	<img src="https://github.com/Karsa-Oy/Mascope/assets/162983707/142a368b-b1f6-4d48-a492-7795c53ca684" width="500"/>
</p>

Sometimes the number of fitted peaks can be different in Tracefinder and Mascope. It usually means that the resolution function for the sample in Mascope is likely incorrect.
