### ISSUE TITLE
Write database create script

### ISSUE THREAD

**Issue by oskarsari** [ultra-trace-systems/mascope#369]
Write a script to create a database from scratch. Pay attention to making sure that the schema is exactly as we want it to be at this point.

**Comment by philip-chernonog** [comment]
Although not addressed separately, the creation of the database using SQLAlchemy models covers the goals of this issue. Check the  [pull request description](https://github.com/Karsa-Oy/Mascope/pull/430#issue-2418594375) for additional information.
