### ISSUE TITLE
Refine SQLAlchemy models

### ISSUE THREAD

**Issue by oskarsari** [ultra-trace-systems/mascope#370]
Revisit SQLAlchemy models for database tables, and make sure they match exactly the intended database schema. This is supposed to be the single truth of database schema in the future.

**Comment by philip-chernonog** [comment]
The adjustments to data types and default values in models addressed this issue in the PR #430 .
Check the  [pull request description](https://github.com/Karsa-Oy/Mascope/pull/430#issue-2418594375) for additional information.
