### ISSUE TITLE
Create database script based on SQLAlchemy

### ISSUE THREAD

**Issue by oskarsari** [ultra-trace-systems/mascope#371]
Write a script to create a database from scratch based on SQLAlchemy models. Compare the result with the raw SQL create script to make sure it's correct. Finally, deprecate the raw SQL script.

**Comment by philip-chernonog** [comment]
This issue was addressed by implementing create_database.py script and was the main focus of  the PR #430 .
Check the  [pull request description](https://github.com/Karsa-Oy/Mascope/pull/430#issue-2418594375) for additional information.
