### ISSUE TITLE
Bugs with heater PID values

### ISSUE THREAD

**Issue by oskarsari** [ultra-trace-systems/mascope#403]
- Heater PID values don't allow two decimals when setting
- Heater PID values reset to default values at application launch?

**Comment by aleu** [comment]
For some reason, github has not traced the fixing commit - so, adding the ref:
https://github.com/Karsa-Oy/KECU/commit/e0dede5ed1f74a827da50c2b9ad781e04b70afa6

**Comment by aleu** [comment]
Update default_values for heater PIDs:  https://github.com/Karsa-Oy/KECU/pull/100/commits/ede52dbc62df6f174e5106d7e5a1906e2d2017a5
