### ISSUE TITLE
Unified Calendar Versioning

### ISSUE THREAD

**Issue by ixxie** [ultra-trace-systems/mascope#415]
## Proposal

Normally the CI/CD system needs to also handle automatic versioning. I don't want to overcomplicate this, so I propose the following:
- We use [Calendar Versioning (CalVer)](https://calver.org/) so our packages get a version like `2024.05.01-23` (the last digit is to support multiple release in one day).
- The version is *global* and stored in a `VERSION` file in the repo root.
- A git precommit hook would automatically update the `VERSION` file whenver we merge to `develop`
- The hook would also sync all `pyproject.toml` files and the frontend's `package.json` to the new version number, even if they didn't change since the last release.
- This hook would also add the version stamp to the git commit message, something like `MASCOPE_VERSION=2024.05.01-23`
- The version number is exposed as a `MASCOPE_VERSION` env var (for DevOps purposes) and somehow exposed directly in the UI (for user support) and printed in the logs on server startup (for log debugging).

## Benefits

This way we:
- Never have to think about after implementing it once
- We don't need to contrive major/minor versions for our apps (SemVer is good for libraries but not clearly defined for apps)
- Are able to correctly asses the version of the build, and find the corresponding git commit by grepping the log for that version
- Have everything we need to support user issues and production bugs

**Comment by ixxie** [comment]
See https://github.com/mahmoud/calver/issues/62 for a discussion of subday versioning.

**Comment by oskarsari** [comment]
I think the versioning schema is sufficient for the time being, closing this issue
