### ISSUE TITLE
Refine user notifications

### ISSUE THREAD

**Issue by oskarsari** [ultra-trace-systems/mascope#455]
Currently, there is a lot of notifications when e.g. computing matches for a batch. Should limit the number of notifications to minimum, either by filtering what to show in the frontend, or what to emit from the backend.

**Comment by philip-chernonog** [comment]
Briefly addressed during #464 in the commit e2995f040599b4b28c6c71df68ce8632baab98ce

UI. Refactor notification handling to reduce redundant notifications
- Updated `push` function to selectively display notifications:
  - Parent process notifications (`process_id` with no `parent_id`) are shown and logged.
  - Child process notifications (`process_id` with `parent_id`) are logged but not displayed.
  - Notifications without `process_id` are shown and logged.
  - Pending notifications are not logged, reducing log entries.

Follow-up:
- Ensure that the rematching process is correctly displayed in the progress bar.

**Comment by philip-chernonog** [comment]
Further addressed in commit 6a47709
- **Centralized notification handling:** Introduced `handleNotification` as the main function to process all incoming notifications. This function decides whether a notification should be displayed, logged, or tracked based on its properties (`process_id`, `parent_id`, `status`).
- **Process notification management:** Implemented a separation between main process notifications and child process notifications:
    - **main process notifications:** (with `process_id` but no `parent_id`) are displayed and logged.
    - **child process notifications:** (with both `process_id` and `parent_id`) are logged but not displayed.
    - **pending notifications:** (with `status` as 'pending') are tracked for progress without logging.
- **Progress tracking:** Refined the tracking of ongoing processes by managing timeouts and cleanup for completed or failed processes.
- **Watcher system:** Documented the watcher system for notifications, ensuring that registered callbacks trigger appropriately based on the type of notification received.
- **Code cleanup:** Improved code readability and maintainability by adding detailed docstrings and comments, ensuring that each function's purpose and behavior are clear.
- **Related issues:**
    - Addressed the excessive notifications issue in #455 by filtering what is shown in the frontend.
    - Resolved the  #359 through the improved notification management logic.
    - Linked to broader concerns in  #464, refining the overall user experience with notifications.
