### ISSUE TITLE
Design notebook server deployment

### ISSUE THREAD

**Issue by oskarsari** [ultra-trace-systems/mascope#470]
How do we serve Jupyter notebooks to the customer

**Comment by ixxie** [comment]
Don't. Publish the API package to PyPi and let the using install Jupyter how they want. An easy [desktop install](https://github.com/jupyterlab/jupyterlab-desktop) is available on all major platforms.

The main advantage: our users are researchers, and many of them will already have established tools and workflows. Forcing them to use a seperate Jupyter environment doesn't allow them to integrate with other tools and data easily. Also, for us Mascope developers: one less thing to deal build, deploy and maintain.

**Comment by oskarsari** [comment]
Publishing the API wrapper is a good solution for users who are familiar with Python/Jupyter already, and I think we should do it.

We still need to make the barrier to start using Jupyter as low as possible also for customers who are not using it yet. Possibly by deploying a Jupyter server, demoing some of the notebooks we have developed for our customers. The obvious caveat would be maintenance cost, so still need to consider our options.

**Comment by ixxie** [comment]
Some options:
- [JupyterLite](https://github.com/jupyterlite/jupyterlite) - client-side kernels using WASM
- [JupyterVerse](https://jupyter-server.github.io/jupyverse/) - FastAPI based deployment server with auth and collaboration

**Comment by oskarsari** [comment]
One more option:

- [voilá](https://voila.readthedocs.io/en/stable/#) - converts the notebook into a little web application preserving interactivity while preventing execution of arbitrary code

**Comment by oskarsari** [comment]
There is obviously also:

- [JupyterHub](https://jupyter.org/hub) - A full-blown multi-user Jupyter server, but I think the maintenance cost puts it out of question

**Comment by oskarsari** [comment]
We have successfully used `voilá` to deploy notebooks. See:
[This PR in Mascope](https://github.com/Karsa-Oy/Mascope/pull/651) and
[this PR in Mascope-Jupyter](https://github.com/Karsa-Oy/Mascope-Jupyter/pull/43)

Follow-up issue #687
