### ISSUE TITLE
Verify intensity dimensions and units

### ISSUE THREAD

**Issue by oskarsari** [ultra-trace-systems/mascope#495]
Make sure signal and peak intensities are calculated correctly for both Orbitrap and TOF, and units are shown correctly in Mascope

**Comment by ghost** [comment]
[Related comment](https://github.com/Karsa-Oy/Mascope/issues/416#issuecomment-2220035089) from the issue #416

**Comment by oskarsari** [comment]
Follow-up issues created based on a review of the current state:

- #588 
- #589 
- #590 
- #591
