### ISSUE TITLE
Negative peak intensity values in Orbitrap files

### ISSUE THREAD

**Issue by oskarsari** [ultra-trace-systems/mascope#497]
Check how and why we have negative peak intensity values in some Orbitrap data file(s)

![kuva (96)](https://github.com/user-attachments/assets/c619235d-ed99-4796-9798-5c636c92084e)

**Comment by ghost** [comment]
I opened all these files directly using the `RawFileReader` and didn't see negative values.

Then I checked if the problem happened on the convertion stage and copied converted files from the server directly. Still no negative values.

Then I loaded fitted peaks (without re-fitting myself). Again, no negative counts.

Maybe I don't understand the issue. @oskarsari or @jussiveh, could you please elaborate?

**Comment by oskarsari** [comment]
> I opened all these files directly using the `RawFileReader` and didn't see negative values.
> 
> Then I checked if the problem happened on the convertion stage and copied converted files from the server directly. Still no negative values.
> 
> Then I loaded fitted peaks (without re-fitting myself). Again, no negative counts.
> 
> Maybe I don't understand the issue. [@oskarsari](https://github.com/oskarsari) or [@jussiveh](https://github.com/jussiveh), could you please elaborate?

The peaks have been refitted after changing the peakshape datatype from `np.float32` -> `np.float64` ([see commit fa3523](https://github.com/Karsa-Oy/Mascope/pull/462/commits/fa35232220814bc6b7e93fe694554f36e02c9fb3)).

Apparently, the change has also resolved this issue. Thanks for checking!
