### ISSUE TITLE
Verify automatic instrument function determination

### ISSUE THREAD

**Issue by oskarsari** [ultra-trace-systems/mascope#514]
Compare peak fitting results from

- current Mascope pipeline
- pipeline augmented with instrument function determination for each file
- batch of TOF data
- batch of Orbitrap data

**Comment by ghost** [comment]
# TOF spectra

We had a TOF file where the algorithm failed to fit a diethylamine peak. We decided to use it as a test file to compare 3 different approaches to calculating the instrument functions. 

- Retrieve instrument functions closest `by time`
- Calculate instrument functions for `each` sample file
- Use the same instrument functions for all sample files with the same settings, I will call it the `batch` approach although the batch may contain sample files with varying settings.

In the picture below, peaks for the comparison were limited by the target list. 

![Verify automatic TOF instrument function determination](https://github.com/user-attachments/assets/57628af0-7a64-4468-be18-08d05e6f0c98)

The current `by time` approach demonstrated the worst performance as expected. The `batch` and `each` approaches were equally effective and allowed for detecting previously unveiled ions.

**Comment by ghost** [comment]
A broader look at the fitted peaks revealed that the `by time` approach detected $\approx 8$%  fewer peaks than `each` and `batch`.

![Peak Effect](https://github.com/user-attachments/assets/3b3c5c2e-87da-4689-9f5c-90a50f479b86)

Below `by time`, `each`, and `batch` are compared in pairs. Not all the differences will be shown but the most typical.

**Comment by ghost** [comment]
## `by time` vs `batch`

In general, `batch` way better detects smaller peaks (102, 125 Th) and better resolves overlapping features (106, 144 Th). There are still arguable cases like the one shown at 55 Th. For me it's hard to say without ground truth which approach is better but @oskarsari has a good point:

> The peak shape tends to have more tail at low masses, and also our resolution function fitting doesn't always fit correctly at low masses. Also, at this low mass it's much more unlikely to have overlaps than at higher masses. So I'm assuming that it's actually a single peak.

![Old vs batch](https://github.com/user-attachments/assets/a309687b-1808-4700-b482-fe120f99e9fd)

**Comment by ghost** [comment]
## `by time` vs `each`

The output is the same as in the case of `by time` vs `batch`. 

![Old vs individual](https://github.com/user-attachments/assets/87b68a9e-1b79-46b5-9591-f621d2936eed)

**Comment by ghost** [comment]
## `each` vs `batch`

The `each` and `batch` approaches perform almost equally. In the case of 117 Th, it is hard to say how many peaks there are. 

![Individual vs batch](https://github.com/user-attachments/assets/6b8cb53d-f64e-411f-9600-dd2c47f2cb8a)

**Comment by ghost** [comment]
## Conclusions for TOF

1. I think it is safe to use the instrument function calculated from the file with the same settings (`batch` approach).
2. The lower m/z range is still poorly fit leading to improper fit in this region. We decided to tackle this in a new issue

**Comment by ghost** [comment]
# Orbitrap spectra

In the Orbitrap case, we couldn't apply the `by time` approach since we found a misalignment in the function used to describe the Orbitrap resolution function. To simulate the `by time` case, I calculated instrument functions from a different batch.

In the case of Orbitrap, the difference between approaches is not that drastic but still notable. 

![Peak Effect Orbi](https://github.com/user-attachments/assets/b82c0ddf-5c23-4bcc-bf96-b76d4de8750c)

**Comment by ghost** [comment]
## `batch` vs `each`

I have found only one case where the fitting is better with the `each` approach (see the upper figure). With all other peaks, the proper fitting is arguable.  

![Individual vs batch orbi](https://github.com/user-attachments/assets/98a10bb2-d2c4-46b1-9f17-7385a4b92be6)

**Comment by ghost** [comment]
## `each` vs `by time`

The difference is similar to what is observed in `batch` vs `each` but more differences in low-intensity peaks. 

![Old vs individual orbi](https://github.com/user-attachments/assets/c594c5da-f9e8-4688-97aa-efc397d9be30)

**Comment by ghost** [comment]
## Conclusions for Orbitrap

The instrument functions between samples in the case of Orbitrap seem to be pretty stable, and recalculation is less critical compared to TOF. However, for better results, it would be still more reliable to use the instrument function calculated from the spectrum with the same settings (`batch` approach).
