### ISSUE TITLE
Design user registration and admin panel

### ISSUE THREAD

**Issue by oskarsari** [ultra-trace-systems/mascope#570]
Design user registration method and an admin panel for managing users:

- New user registration
- User disable / delete
- User role management
- Password reset

**Comment by philip-chernonog** [comment]
Follow-up issues:
**API**
- #648

**UI**

**Comment by oskarsari** [comment]
![Image](https://github.com/user-attachments/assets/b8c455a4-82f3-4226-a709-c26dfa990a6b)
