### ISSUE TITLE
Investigate unnatural isotopic ratios in Trafecinder

### ISSUE THREAD

**Issue by oskarsari** [ultra-trace-systems/mascope#606]
For some reason the isotopic ratio shown in Tracefinder does not match the natural isotopic abundance. The intensity ratio of peaks on the other hand doesn't match the natural isotopic ratio either. Possibly Tracefinder applies some correction to account for nonlinear instrument response?

![Screenshot 2024-10-23 112229](https://github.com/user-attachments/assets/c978b777-c0a0-4a35-b0e4-156dcfd5cc29)
![Screenshot 2024-10-23 112720](https://github.com/user-attachments/assets/283434ca-7a6d-48a9-9eb6-b45653dc5c98)
![Screenshot 2024-10-23 132416](https://github.com/user-attachments/assets/d2df7669-1e15-4f4d-8990-6bdc1ce8d2e9)
![Screenshot 2024-10-21 154306](https://github.com/user-attachments/assets/9025f7e5-bdd2-4dc7-b8cf-eed6a88506ae)

**Comment by ghost** [comment]
I used Isotope Distribution Calculator but with a high-precision calculation method - and got values similar to those observed in Tracefinder.

![image](https://github.com/user-attachments/assets/5c88dbf1-bf50-425b-b732-a03087b53c36)

If we degrade precision to the level we have in Mascope and compare isotope ratios, for example, for 431.13 Th and 432.12 Th, we get approximately the same numbers:

$\text{Isotope Distribution Calculator: }100 / (0.7+25.3+11.9+0.2+0.6) = 2.58$
$\text{Macope: }0.58 / 0.22 = 2.64$

So, in the picture below we separated peaks correctly but didn't calculate the expected target isotope mass with enough precision.

![image](https://github.com/user-attachments/assets/24b032d6-8029-4f94-9248-81768cb29faf)

We have created a new issue #641 to address the calculation precision.
