### ISSUE TITLE
Implement secret management for sensitive data

### ISSUE THREAD

**Issue by philip-chernonog** [ultra-trace-systems/mascope#646]
Develop a secure and organized system for handling sensitive data within the app, such as:

- Mascope [private key](https://github.com/Karsa-Oy/Mascope/blob/ebf6bf98f6c9cb146b45d8d49b045b407ceda777/backend/mascope_server/api/new/auth/config.py#L14-L16) (used for [JWT generation](https://github.com/Karsa-Oy/Mascope/blob/ebf6bf98f6c9cb146b45d8d49b045b407ceda777/backend/mascope_server/api/new/auth/auth_backend.py#L53-L58) ). 
- Owner account credentials.

**Comment by oskarsari** [comment]
I propose to use environment variables, with a possibility to override them from a `.env` file. So basically a combination of point 1 and 2 [in this blog post](https://blog.gitguardian.com/how-to-handle-secrets-in-python/)
