### ISSUE TITLE
Experiment with JupyterLite for instrument function evaluation notebook

### ISSUE THREAD

**Issue by ghost** [ultra-trace-systems/mascope#650]
This is a follow-up of issue #631 

https://jupyterlite.readthedocs.io/en/stable/

**Comment by ghost** [comment]
# How the things are set up

To install JupyterLite CLI we use something like: 

```bash
python -m pip install jupyterlite-core
```

JupyterLite requires its own Jupyter kernel and environment, [Pyodide-based](https://pyodide.org/en/stable/index.html). To install it:

```bash
python -m pip install jupyterlite-pyodide-kernel
```
To set up the JupyterLite project, we cd to the folder and run there:

```bash
jupyter lite init
jupyter lite build
```

Then, to run the server:

```bash
jupyter lite serve
```

# How do I install modules?

The recommended method is using [micropip](https://micropip.pyodide.org/en/stable/project/usage.html):

```Python
import micropip
await micropip.install("numpy")
```

To install custom modules, we should first pack them into wheel format.
In poetry, we go to the folder with a module and run:

> poetry build

This will create a .whl file in the `dist` folder. Then, to install the package, we may use:

```Python
import micropip
await micropip.install("path_or_url_to_build/package.whl")
```
And here is the start of the main problems. Where do we store whl-files? How do we keep our internal libraries up to date? How do we prevent the user from reading the course code? How do we align our poetry environment with the Jupyter Lite? This seems to be an unnecessary hassle given the simplicity of Voila. 

# Other potential issues

- Jupyter Lite is just like the common Jupyter Notebook. It does not allow for hiding cells or focusing on one notebook only.
- The Pyodide kernel may not support complex computations and visualizations due to performance problems.
- Not every Python library is available for installation within micropip. 

# Are there other ways to use it?

We could probably use it for data analysis applications when a user has a template and gets data through API, then keeps processing in the way they want. I still doubt this is more convenient than using Google Colab or deploying JupyterHub.

# My conclusion

Voila is still a better way to go.

**Comment by oskarsari** [comment]
Thank you for the write up, let's continue experimenting with voilá
