### ISSUE TITLE
UI bugs report

### ISSUE THREAD

**Issue by philip-chernonog** [ultra-trace-systems/mascope#657]
**Attribute templates**
- [x] Cant delete attribute template
  
  <details><summary>Details</summary>
  <p>
  
  ![image](https://github.com/user-attachments/assets/b58d82d9-e181-4de9-8656-8fb04e2927fa)
  
  
  </p>
  </details> 

- [x] The option `default (modified)` should appear after you start the editing button (new templete creation without saving?). Currently it is available immediately
  <details><summary>Details</summary>
  <p>
  
  ![image](https://github.com/user-attachments/assets/996a5423-d5cd-4f12-a707-937593e986e3)
  
  
  </p>
  </details> 

**Selection**

- [x]  After rematching a sample, selected targets are not properly reloaded. Matches are not updated in a TargetBrowser if a target is selected before rematching.
- [x]  If a target ion is selected in the target browser, after rematching a sample, the `target_ion` data is not passed, causing a "target ion not found" error in the Match tab visualization.
- [x] "+" button to create a compound directly from target collection also toggles the selection, causing "auto-scroll" to hide the dialog
  <details><summary>Details for both issues</summary>
  <p>
  
  ![image](https://github.com/user-attachments/assets/c49693bc-4343-4234-8c3a-a2056cd10c0c)
  

  https://github.com/user-attachments/assets/9bf8e6b9-d8ca-4620-99e9-f321a32358f5

  
  </p>
  </details>

**Comment by oskarsari** [comment]
- [x] There is also issue #654 which could be addressed together with other bug fixes
